image: cirrusci/flutter:latest

before_script:
  - git submodule update --init --recursive
  - flutter pub get
  - flutter --version
stages:
  - test
  - build

lint_and_test:
  stage: test
  only:
    - merge_requests
  script:
    - flutter analyze
    - flutter test ./